//---------------------------------------------------------------------------

#ifndef Unit5H
#define Unit5H
//---------------------------------------------------------------------------
#include <System.Classes.hpp>
#include <Vcl.Controls.hpp>
#include <Vcl.StdCtrls.hpp>
#include <Vcl.Forms.hpp>
#include <Vcl.ExtCtrls.hpp>
#include <Vcl.Graphics.hpp>
//---------------------------------------------------------------------------
class TForm5 : public TForm
{
__published:	// IDE-managed Components
	TPanel *LeftBlock;
	TButton *Back;
	TPanel *RightBlock;
	TButton *Next;
	TScrollBox *ScrollBox1;
	TPanel *List7;
	TLabel *Topik7;
	TMemo *Memo7_1;
	TPanel *Panel5;
	TImage *Image7_1;
	TMemo *Memo7_2;
	TPanel *Panel6;
	TMemo *Memo7_3;
	TPanel *Answer7;
	TPanel *Panel7;
	TPanel *List19;
	TLabel *Label7;
	TMemo *Memo14;
	TPanel *List18;
	TLabel *Label3;
	TMemo *Memo7;
	TPanel *List17;
	TLabel *Label5;
	TLabel *Label6;
	TImage *Image6;
	TPanel *Panel8;
	TMemo *Memo11;
	TMemo *Memo12;
	TMemo *Memo13;
	TPanel *Panel38;
	TPanel *List16;
	TLabel *Topic17;
	TLabel *Titel17;
	TImage *Image16_1;
	TPanel *Scoba16;
	TMemo *Memo16_1;
	TMemo *Memo16_2;
	TMemo *Memo16_3;
	TPanel *Panel37;
	TPanel *List15;
	TLabel *Topic15;
	TLabel *Titel15;
	TImage *Image15_3;
	TPanel *Scoba15;
	TMemo *Memo15_1;
	TMemo *Memo15_2;
	TMemo *Memo15_9;
	TPanel *Panel3;
	TPanel *Panel31;
	TMemo *Memo15_8;
	TMemo *Memo15_7;
	TPanel *Panel32;
	TImage *Image15_1;
	TPanel *Answer15_2;
	TPanel *Panel33;
	TMemo *Memo15_3;
	TMemo *Memo15_4;
	TPanel *Panel34;
	TImage *Image15_2;
	TPanel *Answer15_3;
	TPanel *Panel36;
	TMemo *Memo15_5;
	TMemo *Memo15_6;
	TPanel *Panel35;
	TImage *Image15_4;
	TPanel *Answer15_1;
	TPanel *List14;
	TLabel *Topic14;
	TLabel *Titel14;
	TImage *Image14_1;
	TPanel *Scoba14;
	TMemo *Memo14_1;
	TMemo *Memo14_2;
	TMemo *Memo14_3;
	TPanel *Panel30;
	TPanel *List13;
	TLabel *Topic13;
	TLabel *Title13;
	TImage *Image13;
	TPanel *Scoba13;
	TMemo *Memo13_1;
	TMemo *Memo13_2;
	TMemo *Memo13_3;
	TPanel *Panel29;
	TPanel *List12;
	TLabel *Topic12;
	TLabel *Titel12;
	TImage *Image12_1;
	TPanel *Scoba12;
	TMemo *Memo12_1;
	TMemo *Memo12_2;
	TMemo *Memo12_7;
	TMemo *Memo12_8;
	TMemo *Memo10;
	TPanel *Panel24;
	TImage *Image12_2;
	TPanel *Answer12_3;
	TPanel *Panel25;
	TPanel *Panel26;
	TMemo *Memo5;
	TMemo *Memo6;
	TPanel *Panel27;
	TMemo *Memo12_5;
	TMemo *Memo12_6;
	TPanel *Panel28;
	TImage *Image12_4;
	TPanel *Answer12_1;
	TPanel *Panel22;
	TImage *Image12_3;
	TPanel *Answer12_2;
	TPanel *List11;
	TLabel *Topic11;
	TLabel *Title11;
	TImage *Image1;
	TMemo *Memo11_2;
	TMemo *Memo11_1;
	TPanel *List9;
	TImage *Image9_1;
	TPanel *Panel13;
	TLabel *Title9;
	TLabel *Topik9;
	TPanel *Scoba9_1;
	TMemo *Memo9_1;
	TMemo *Memo9_2;
	TMemo *Memo9_7;
	TPanel *Panel14;
	TMemo *Memo9_6;
	TMemo *Memo9_3;
	TPanel *Panel15;
	TImage *Image9_2;
	TPanel *Answer9_2;
	TPanel *Panel16;
	TImage *Image9_3;
	TPanel *Answer9_1;
	TPanel *Panel17;
	TMemo *Memo9_5;
	TMemo *Memo9_4;
	TPanel *List6;
	TLabel *Topic6;
	TLabel *Title6;
	TPanel *Scoba6_1;
	TImage *Image6_1;
	TMemo *Memo6_2;
	TMemo *Memo6_1;
	TMemo *Memo6_3;
	TPanel *Panel4;
	TPanel *Panel2;
	TImage *Image6_2;
	TPanel *Answer6;
	TMemo *Memo6_4;
	TPanel *List5;
	TImage *Image3;
	TPanel *List4;
	TLabel *VVed;
	TMemo *Memo2;
	TPanel *List10;
	TImage *Image10_1;
	TPanel *Scobca10;
	TMemo *Memo10_1;
	TMemo *Memo10_2;
	TPanel *Panel18;
	TLabel *Title10;
	TLabel *Topic10;
	TPanel *Panel19;
	TMemo *Memo10_5;
	TMemo *Memo10_6;
	TPanel *Panel20;
	TImage *Image10_2;
	TPanel *Answer10_1;
	TPanel *Panel21;
	TMemo *Memo10_3;
	TMemo *Memo10_4;
	TMemo *Memo1;
	TPanel *Panel23;
	TImage *Image10_3;
	TPanel *Answer10_2;
	TPanel *List1;
	TImage *Image2;
	TMemo *Memo3;
	TMemo *Memo4;
	TPanel *List3;
	TLabel *ogl;
	TPanel *Panel1;
	TLabel *Link4;
	TLabel *Link6;
	TLabel *Link7;
	TLabel *Link8;
	TLabel *Link9;
	TLabel *Link10;
	TLabel *Link11;
	TLabel *Link12;
	TLabel *Link13;
	TLabel *Link14;
	TLabel *Link15;
	TLabel *Link16;
	TLabel *Link17;
	TLabel *Label1;
	TLabel *Label2;
	TPanel *List2;
	TLabel *NameProject;
	TMemo *Bysuv;
	TMemo *Byruk;
	TPanel *List8;
	TLabel *Topik8;
	TLabel *Title8;
	TImage *Image8_1;
	TMemo *Memo8_7;
	TPanel *Panel9;
	TMemo *Memo8_3;
	TMemo *Memo8_4;
	TPanel *Panel10;
	TImage *Image8_2;
	TPanel *Answer8_1;
	TPanel *Panel11;
	TMemo *Memo8_5;
	TMemo *Memo8_6;
	TPanel *Panel12;
	TImage *Image8_3;
	TPanel *Answer8_2;
	void __fastcall FormCreate(TObject *Sender);
	void __fastcall FormDblClick(TObject *Sender);
	void __fastcall FormMouseDown(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall FormMouseMove(TObject *Sender, TShiftState Shift, int X, int Y);
	void __fastcall FormMouseUp(TObject *Sender, TMouseButton Button, TShiftState Shift,
          int X, int Y);
	void __fastcall BackClick(TObject *Sender);
	void __fastcall NextClick(TObject *Sender);

private:	// User declarations
public:		// User declarations
	__fastcall TForm5(TComponent* Owner);
};
//---------------------------------------------------------------------------
extern PACKAGE TForm5 *Form5;
//---------------------------------------------------------------------------
#endif
